use cc_daemon::{
    commands, files,
    store::{Store, id, now},
};
use serde_json::{Value, json};
use std::{
    fs,
    io::Write,
    path::Path,
    process::{Command, Stdio},
    thread,
    time::{Duration, Instant},
};

fn rpc(workspace: &Path, name: &str, args: Value) -> Value {
    let mut child = Command::new(env!("CARGO_BIN_EXE_cruise"))
        .args(["mcp", "--workspace"])
        .arg(workspace)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    let mut input = child.stdin.take().unwrap();
    writeln!(input, "{}", json!({"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-11-25","clientInfo":{"name":"command-test","version":"1"},"capabilities":{}}})).unwrap();
    writeln!(input, "{}", json!({"jsonrpc":"2.0","id":2,"method":"tools/call","params":{"name":name,"arguments":args}})).unwrap();
    drop(input);
    let output = child.wait_with_output().unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let last: Value = serde_json::from_str(
        String::from_utf8_lossy(&output.stdout)
            .lines()
            .last()
            .unwrap(),
    )
    .unwrap();
    assert!(last.get("error").is_none(), "{last}");
    assert_ne!(last["result"]["isError"], true, "{last}");
    serde_json::from_str(last["result"]["content"][0]["text"].as_str().unwrap()).unwrap()
}
fn wait(store: &Store, run: &Value) -> Value {
    let start = Instant::now();
    loop {
        let value = commands::call(
            store,
            "read_course_command",
            json!({"courseId":"course","runId":run["id"]}),
        )
        .unwrap();
        if !matches!(value["status"].as_str(), Some("queued" | "running")) {
            return value;
        }
        assert!(
            start.elapsed() < Duration::from_secs(15),
            "command did not finish: {value}"
        );
        thread::sleep(Duration::from_millis(50));
    }
}

#[cfg(unix)]
#[test]
fn detached_binary_worker_survives_mcp_exit_and_cancels_its_process_group() {
    let root = std::env::temp_dir().join(format!("cruise-native-command-{}", id()));
    let store = Store { root: root.clone() };
    store.mutate(|state| {
        state["courses"] = json!([{"id":"course","code":"CMD","name":"Test"}]);
        state["assignments"] = json!([{"id":"assignment","courseId":"course","title":"Commands","createdAt":now()}]);
        Ok(())
    }).unwrap();
    let run = rpc(
        &root,
        "run_course_command",
        json!({"courseId":"course","assignmentId":"assignment","location":"assignment","command":"sleep 0.2; printf 'durable output'; printf 'generated by the Rust worker' > generated.txt","purpose":"Check a detached Rust worker after its parent exits","timeoutSeconds":5}),
    );
    let completed = wait(&store, &run);
    assert_eq!(completed["status"], "completed", "{completed}");
    assert_eq!(completed["exitCode"], 0);
    assert_eq!(completed["output"], "durable output");
    assert_eq!(
        files::call(
            &store,
            "read_assignment_file",
            json!({"courseId":"course","assignmentId":"assignment","path":"generated.txt"})
        )
        .unwrap()["content"],
        "generated by the Rust worker"
    );
    assert!(
        store
            .path(completed["summaryPath"].as_str().unwrap())
            .unwrap()
            .is_file()
    );

    let running = rpc(
        &root,
        "run_course_command",
        json!({"courseId":"course","command":"sleep 60 & printf '%s' \"$!\" > child.pid; wait","purpose":"Verify cancellation of command descendants","timeoutSeconds":60}),
    );
    let child_pid = root.join("courses/course/files/child.pid");
    let start = Instant::now();
    while !child_pid.exists() {
        assert!(start.elapsed() < Duration::from_secs(5));
        thread::sleep(Duration::from_millis(25));
    }
    rpc(
        &root,
        "stop_course_command",
        json!({"courseId":"course","runId":running["id"]}),
    );
    let stopped = wait(&store, &running);
    assert_eq!(stopped["status"], "cancelled", "{stopped}");
    let pid = fs::read_to_string(child_pid).unwrap();
    assert!(pid.trim().parse::<u32>().is_ok());
    let process = fs::read_to_string(format!("/proc/{}/stat", pid.trim()));
    assert!(
        process.is_err() || process.unwrap().split_whitespace().nth(2) == Some("Z"),
        "child process survived cancellation"
    );
    assert!(root.starts_with(std::env::temp_dir()));
    fs::remove_dir_all(root).unwrap();
}
